services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=customer_support.settings
      - GROK_API_KEY=${GROK_API_KEY:-your-grok-api-key-here}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-api-key-here}
    env_file:
      - .env
