# Generated by Django 4.2.7 on 2025-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
